#  This file is part of the RomCom Python Package <https://github.com/miltonra/RomCom>
#
#  Copyright (C) 2027 Robert A. Milton
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

""" Benchmark GPR and GSA for known test functions. """

from rc.base.definitions import *

from rc import task

#: Parameters to generate data from test functions.
K: int = 2  #: The number of Folds in a new repository.
Ms: Tuple[int, ...] = (7, )  #: The number of inputs.
Ns: Tuple[int, ...] = (300, )   #: The number of samples (datapoints).
DOE: rc.data.sample.DOE.Method = rc.data.sample.DOE.latin_hypercube   #: The Design Of Experiments to generate the sample inputs.
FUNCTION_VECTOR: rc.data.functions.Vector = rc.data.functions.OAKLEY2004  #: The function vector to apply to the inputs generated by the DOE.
NOISE_MAGNITUDES: Tuple[float] = (0.04, )    #: The noise-to-signal ratio, which is equal to the StdDev of the noise added to the normalised function output.
IS_NOISE_COVARIANT: bool = False  #: Whether the Gaussian noise applied to the outputs is statistically independent between outputs.
IS_NOISE_VARIANCE_DETERMINED: bool = True  #: Whether the noise variance is fixed or random.
ROTATIONS = {'': None}  #: Dict of rotations applied to the input basis after the function vector has been sampled.
#: Parameters to task Gaussian Process Regression.
IS_GPR_READ: bool | None = False  #: Whether to read the GPR model from file.
IS_GPR_COVARIANT: bool | None = False  #: Whether the GPR likelihood is covariant.
IS_GPR_ISOTROPIC: bool | None = None  #: Whether the GPR kernel is isotropic.
#: Parameters to task Global Sensitivity Analysis.
GSA_KINDS: List[task.run.GSA.Kind] = task.run.GSA.ALL_KINDS  #: A list of the kinds of GSA to do.
IS_GSA_ERROR_CALCULATED: bool = True  #: Whether to calculate the GSA standard error
IS_GSA_ERROR_PARTIAL: bool = False  #: Whether the calculated the GSA standard error is partial


def run(root: str | Path) -> Path:
    """ Run benchmark data generation and/or Gaussian Process Regression and/or Global Sensitivity Analysis, and collect the results.

    Args:
        root: The root folder.
    Returns: The root path written to.
    """
    with run.contexts.Environment('Test', device= '/CPU'):
        KIND_NAMES = [kind.name.lower() for kind in GSA_KINDS]
        for noise_magnitude in NOISE_MAGNITUDES:
            for M in Ms:
                for N in Ns:
                    noise_variance = rc.data.sample.GaussianNoise.Variance(len(FUNCTION_VECTOR), noise_magnitude, IS_NOISE_COVARIANT, IS_NOISE_VARIANCE_DETERMINED)
                    for rotation_name, rotation in ROTATIONS.items():
                        with run.contexts.Timer(f'M={M}, N={N}, noise={noise_magnitude}', is_inline=False):

                            # Get data sample, either from function or file.
                            repo = rc.data.sample.Function(root, DOE, FUNCTION_VECTOR, N, M, noise_variance, None,
                                                           True).repo.into_K_folds(K).rotate_folds(rotation)

                            # Run GPR, or collect stored GPR models.
                            models = run.run.gpr(name= 'gpr', repo=repo, is_read=IS_GPR_READ, is_covariant=IS_GPR_COVARIANT,
                                                 is_isotropic=IS_GPR_ISOTROPIC, ignore_exceptions=False)

                            # Collect GPR results from GPR models.
                            run.results.Collect({'test': {'header': [0, 1]}, 'test_summary': {'header': [0, 1], 'index_col': 0}},
                                                {repo.folder / model: {'model': model} for model in models},
                                                False).from_folders(repo.folder / 'gpr', True)
                            run.results.Collect({'variance': {}, 'log_marginal': {}},
                                                {f'{repo.folder / model}/likelihood': {'model': model} for model in models},
                                                False).from_folders((repo.folder / 'gpr') / 'likelihood', True)
                            run.results.Collect({'variance': {}, 'lengthscales': {}},
                                                {f'{repo.folder / model}/kernel': {'model': model} for model in models},
                                                False).from_folders((repo.folder / 'gpr') / 'kernel', True)

                            # Run GSA and collect results, or just collect results.
                            run.run.gsa('gpr', repo, is_covariant=IS_GPR_COVARIANT, is_isotropic=False, kinds=GSA_KINDS,
                                        is_error_calculated=IS_GSA_ERROR_CALCULATED, ignore_exceptions=False, is_T_partial=IS_GSA_ERROR_PARTIAL)
                            run.results.Collect({'S': {}, 'V': {}} | ({'T': {}, 'W': {}} if IS_GSA_ERROR_CALCULATED else {}),
                                                {f'{repo.folder / model}/gsa/{kind_name}': {'model': model, 'kind': kind_name}
                                                  for kind_name in KIND_NAMES for model in models},
                                                True).from_folders((repo.folder / 'gsa'), True)
    return root


if __name__ == '__main__':

    # Run the code.
    root = Path('installation_test')
    print(f'Root path is {run(root)}')
